name: Test Validation on Multiple OS

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, ubuntu-20.04]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (Linux & macOS)
        if: runner.os != 'Windows'
        run: |
          sudo apt update || true
          sudo apt install -y build-essential cmake || true

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install mingw -y

      - name: Build project
        run: |
          mkdir build
          # cmake -DCMAKE_BUILD_TYPE=Release -S . -B build
          # cmake --build build

      - name: Run tests
        run: |
          # chmod +x tests/run-tests.sh || true
          # ./tests/run-tests.sh || exit 1
